import type { Config } from 'tailwindcss'
import colors from 'tailwindcss/colors'
import defaultTheme from 'tailwindcss/defaultTheme'
import tailwindcssAnimate from 'tailwindcss-animate'

const config: Config = {
  darkMode: ['class', '.dark'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    screens: defaultTheme.screens,
    fontWeight: defaultTheme.fontWeight,
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
        black: '#000000',
        white: '#ffffff',
        slate: colors.slate,
        gray: colors.gray,
        zinc: colors.zinc,
        neutral: colors.neutral,
        stone: colors.stone,
        red: colors.red,
        orange: colors.orange,
        amber: colors.amber,
        yellow: colors.yellow,
        lime: colors.lime,
        green: colors.green,
        emerald: colors.emerald,
        teal: colors.teal,
        cyan: colors.cyan,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        violet: colors.violet,
        purple: colors.purple,
        fuchsia: colors.fuchsia,
        pink: colors.pink,
        rose: colors.rose,
        // Brand colors — reference CSS variables defined in globals.css
        primary: {
          DEFAULT: 'hsl(var(--color-primary))',
          dark: 'hsl(var(--color-primary-dark))',
          light: 'hsl(var(--color-primary-light))',
          hover: 'hsl(var(--color-primary-hover))',
          foreground: 'hsl(var(--color-primary-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--color-accent))',
          dark: 'hsl(var(--color-accent-dark))',
          soft: 'hsl(var(--color-accent-soft))',
          hover: 'hsl(var(--color-accent-hover))',
          foreground: 'hsl(var(--color-accent-foreground))',
        },
        cta: {
          DEFAULT: 'hsl(var(--color-cta))',
          hover: 'hsl(var(--color-cta-hover))',
          foreground: 'hsl(var(--color-cta-foreground))',
        },
        background: 'hsl(var(--color-background))',
        dark: 'hsl(var(--color-navy))',
        surface: {
          DEFAULT: 'hsl(var(--color-surface))',
          soft: 'hsl(var(--color-surface-soft))',
          hover: 'hsl(var(--color-surface-hover))',
        },
        navy: 'hsl(var(--color-navy))',
        muted: 'hsl(var(--color-muted))',
        border: {
          DEFAULT: 'hsl(var(--color-border))',
          soft: 'hsl(var(--color-border-soft))',
          strong: 'hsl(var(--color-border-strong))',
        },
        text: {
          primary: 'hsl(var(--color-text-primary))',
          secondary: 'hsl(var(--color-text-secondary))',
          muted: 'hsl(var(--color-text-muted))',
          inverse: 'hsl(var(--color-text-inverse))',
        },
        success: {
          DEFAULT: 'hsl(var(--color-success))',
          soft: 'hsl(var(--color-success-soft))',
        },
        error: 'hsl(var(--color-error))',
        warning: {
          DEFAULT: 'hsl(var(--color-warning))',
          soft: 'hsl(var(--color-warning-soft))',
        },
        card: {
          DEFAULT: 'hsl(var(--color-surface))',
          foreground: 'hsl(var(--color-text-primary))',
        },
        popover: {
          DEFAULT: 'hsl(var(--color-background))',
          foreground: 'hsl(var(--color-text-primary))',
        },
        mutedUi: {
          DEFAULT: 'hsl(var(--color-surface))',
          foreground: 'hsl(var(--color-text-muted))',
        },
        input: 'hsl(var(--color-border))',
        ring: 'hsl(var(--color-primary))',
        destructive: {
          DEFAULT: 'hsl(var(--color-error))',
          foreground: 'hsl(var(--color-text-inverse))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--color-surface))',
          foreground: 'hsl(var(--color-text-primary))',
        },
        foreground: 'hsl(var(--color-text-primary))',
      },
      fontFamily: {
        display: ['var(--font-display)', 'serif'],
        body: ['var(--font-body)', 'sans-serif'],
        mono: ['var(--font-mono)', 'monospace'],
        sans: ['var(--font-body)', 'sans-serif'],
      },
      fontSize: {
        ...defaultTheme.fontSize,
        'display-2xl': ['4.5rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-xl': ['3.75rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-lg': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.02em' }],
        'display-md': ['2.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
        'display-sm': ['1.875rem', { lineHeight: '1.25', letterSpacing: '-0.01em' }],
        'body-xl': ['1.25rem', { lineHeight: '1.75' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75' }],
        'body-md': ['1rem', { lineHeight: '1.6' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5' }],
        'body-xs': ['0.75rem', { lineHeight: '1.5' }],
      },
      spacing: {
        '0.5': '2px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '2.5': '10px',
        '3': '12px',
        '3.5': '14px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '18': '72px',
        '20': '80px',
        '24': '96px',
        '28': '112px',
        '32': '128px',
        '36': '144px',
        '40': '160px',
        '44': '176px',
        '48': '192px',
        '52': '208px',
        '56': '224px',
        '60': '240px',
        '64': '256px',
        '72': '288px',
        '80': '320px',
        '96': '384px',
      },
      borderRadius: {
        none: '0px',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        DEFAULT: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        card: 'var(--radius-card)',
        button: 'var(--radius-button)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: '9999px',
      },
      boxShadow: {
        'shadow-xs': 'var(--shadow-xs)',
        'shadow-sm': 'var(--shadow-sm)',
        'shadow-md': 'var(--shadow-md)',
        'shadow-lg': 'var(--shadow-lg)',
        'shadow-xl': 'var(--shadow-xl)',
        'shadow-2xl': 'var(--shadow-2xl)',
        'shadow-inner': 'var(--shadow-inner)',
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        soft: 'var(--shadow-soft)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'none',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        normal: 'var(--duration-normal)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
      transitionTimingFunction: {
        'ease-smooth': 'var(--ease-smooth)',
        'ease-spring': 'var(--ease-spring)',
        'ease-bounce': 'var(--ease-bounce)',
        'ease-in-expo': 'var(--ease-in-expo)',
        'ease-out-expo': 'var(--ease-out-expo)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
        'fade-in': {
          from: { opacity: '0' },
          to: { opacity: '1' },
        },
        'fade-out': {
          from: { opacity: '1' },
          to: { opacity: '0' },
        },
        'slide-up': {
          from: { transform: 'translateY(16px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-down': {
          from: { transform: 'translateY(-16px)', opacity: '0' },
          to: { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-right': {
          from: { transform: 'translateX(100%)' },
          to: { transform: 'translateX(0)' },
        },
        'slide-out-right': {
          from: { transform: 'translateX(0)' },
          to: { transform: 'translateX(100%)' },
        },
        'scale-in': {
          from: { transform: 'scale(0.95)', opacity: '0' },
          to: { transform: 'scale(1)', opacity: '1' },
        },
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'pulse-soft': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        shimmer: {
          from: { backgroundPosition: '-200% 0' },
          to: { backgroundPosition: '200% 0' },
        },
        'toast-in': {
          from: { transform: 'translateX(calc(100% + 1rem))', opacity: '0' },
          to: { transform: 'translateX(0)', opacity: '1' },
        },
        'toast-out': {
          from: { transform: 'translateX(0)', opacity: '1' },
          to: { transform: 'translateX(calc(100% + 1rem))', opacity: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'fade-out': 'fade-out 0.2s ease-in',
        'slide-up': 'slide-up 0.4s ease-out',
        'slide-down': 'slide-down 0.4s ease-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-out-right': 'slide-out-right 0.3s ease-in',
        'scale-in': 'scale-in 0.2s ease-out',
        'spin-slow': 'spin-slow 3s linear infinite',
        'pulse-soft': 'pulse-soft 2s ease-in-out infinite',
        shimmer: 'shimmer 2s linear infinite',
        'toast-in': 'toast-in 0.35s cubic-bezier(0.21, 1.02, 0.73, 1)',
        'toast-out': 'toast-out 0.4s ease-in forwards',
      },
      maxWidth: {
        'screen-xs': '480px',
        'screen-sm': '640px',
        'screen-md': '768px',
        'screen-lg': '1024px',
        'screen-xl': '1280px',
        'screen-2xl': '1400px',
        content: '720px',
        wide: '1100px',
      },
      zIndex: {
        'z-base': 'var(--z-base)',
        'z-dropdown': 'var(--z-dropdown)',
        'z-sticky': 'var(--z-sticky)',
        'z-overlay': 'var(--z-overlay)',
        'z-modal': 'var(--z-modal)',
        'z-popover': 'var(--z-popover)',
        'z-toast': 'var(--z-toast)',
        'z-tooltip': 'var(--z-tooltip)',
      },
    },
  },
  plugins: [tailwindcssAnimate],
}

export default config
