import {
  ArrowLeft,
  ArrowRight,
  ImagePlus,
  Languages,
  Layers3,
  Maximize2,
  Menu,
  Redo2,
  RotateCcw,
  Save,
  Search,
  Settings,
  Share2,
  ShoppingBag,
  Trash2,
  Type,
  Undo2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
  type LucideIcon,
} from "lucide-react";

const FLUENT_EMOJI_ROOT = "/assets/icons/fluent-emoji";

export const DECORATIVE_ICON_PATHS = {
  artistPalette: `${FLUENT_EMOJI_ROOT}/artist-palette-3d.png`,
  briefcase: `${FLUENT_EMOJI_ROOT}/briefcase-3d.png`,
  calendar: `${FLUENT_EMOJI_ROOT}/calendar-3d.png`,
  camera: `${FLUENT_EMOJI_ROOT}/camera-3d.png`,
  chartIncreasing: `${FLUENT_EMOJI_ROOT}/chart-increasing-3d.png`,
  checkMark: `${FLUENT_EMOJI_ROOT}/check-mark-3d.png`,
  deliveryTruck: `${FLUENT_EMOJI_ROOT}/delivery-truck-3d.png`,
  envelope: `${FLUENT_EMOJI_ROOT}/envelope-3d.png`,
  framedPicture: `${FLUENT_EMOJI_ROOT}/framed-picture-3d.png`,
  graduationCap: `${FLUENT_EMOJI_ROOT}/graduation-cap-3d.png`,
  handshake: `${FLUENT_EMOJI_ROOT}/handshake-3d.png`,
  highVoltage: `${FLUENT_EMOJI_ROOT}/high-voltage-3d.png`,
  identificationCard: `${FLUENT_EMOJI_ROOT}/identification-card-3d.png`,
  megaphone: `${FLUENT_EMOJI_ROOT}/megaphone-3d.png`,
  officeBuilding: `${FLUENT_EMOJI_ROOT}/office-building-3d.png`,
  package: `${FLUENT_EMOJI_ROOT}/package-3d.png`,
  receipt: `${FLUENT_EMOJI_ROOT}/receipt-3d.png`,
  shield: `${FLUENT_EMOJI_ROOT}/shield-3d.png`,
  sparkles: `${FLUENT_EMOJI_ROOT}/sparkles-3d.png`,
  telephoneReceiver: `${FLUENT_EMOJI_ROOT}/telephone-receiver-3d.png`,
  trophy: `${FLUENT_EMOJI_ROOT}/trophy-3d.png`,
  wrappedGift: `${FLUENT_EMOJI_ROOT}/wrapped-gift-3d.png`,
} as const;

export const FUNCTIONAL_ICONS = {
  addText: Type,
  addImage: ImagePlus,
  upload: Upload,
  undo: Undo2,
  redo: Redo2,
  delete: Trash2,
  share: Share2,
  save: Save,
  cart: ShoppingBag,
  next: ArrowRight,
  previous: ArrowLeft,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
  fitScreen: Maximize2,
  resetZoom: RotateCcw,
  layers: Layers3,
  search: Search,
  settings: Settings,
  close: X,
  menu: Menu,
  language: Languages,
} as const satisfies Record<string, LucideIcon>;

export type FunctionalIconName = keyof typeof FUNCTIONAL_ICONS;
